trigger:none

stages:
  - stage: Build
    displayName: 'Build stage'
    jobs:
      - job: Build
        displayName: 'Build job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
              version: '6.x'
          - script: dotnet build --configuration Release

  - stage: Test
    displayName: 'Test stage'
    dependsOn: Build
    jobs:
      - job: Test
        displayName: 'Test job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
              version: '6.x'
          - script: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"

  - stage: Deploy
    displayName: 'Deploy stage'
    dependsOn: Test
    jobs:
      - job: Deploy
        displayName: 'Deploy job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - script: echo 'TODO - Deployment'
